"""empty message

Revision ID: 0e58a5dfe447
Revises: 0ead6c12fd4c
Create Date: 2026-02-14 14:13:23.316487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e58a5dfe447'
down_revision = '0ead6c12fd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('owner_username')

    # ### end Alembic commands ###
