# Generated by Django 6.0.1 on 2026-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_playsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='playsession',
            name='current_page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
